### ISSUE TITLE
Is it possible to "execute a gem"?

### ISSUE THREAD

**Issue by Dispader** [jruby-gradle/jruby-gradle-plugin#103]
Hey there,

  I'm really sorry to trouble— this is probably a very rudimentary question.

  I have a project that has a `Gemfile` (with the `guard-gradle` gem defined), and I'm currently using `bundle`, `bundle exec guard` to "execute the gem."  I can't say that I know how bundler performs the execution, though.

  I've added the plugin and successfully resolved the dependencies, but I can't seem to find a way to execute the installed Gem— I've tried using the `JRubyExec` task type, but it seems to very much want a script (which makes sense).

  Is it possible to use the plugin's gem resolution, but "execute" a gem directly from a task?

  Sorry again to trouble— and thank you for the wonderful project.

**Comment by ysb33r** [comment]
Try passing
```groovy
  scriptArgs '-S'
  script 'guard'
```
in the configuration closure. The way `JRubyExec` operates is to use the `bin` directory to look for scripts if `script` is not absolute and if `scriptArgs` contains `-S`.

**Comment by ysb33r** [comment]
OK, I've played a bit with `guard-gradle` and asis the above won't work. One reason is that that `guard-gradle` does nto have a `bin` folder and secondly for `guard-gradle` to work you need to do additional setup work i.e. run the `installer.sh` script.

The problem is that the default script will try to `gem install` to your standard GEM installation folder, something which we try to avoid within the plugin with good reason.

I am just not even sure running it from Gradle will work correctly (even if you set `scriptArgs "${gemInstallDir}/guard-gradle-0.5/0/lib/gradle.rb"`). You are effectively creating a watcher which I am not sure will survive a Gradle exit.

**Comment by Dispader** [comment]
Thank you, sir!  That was helpful.

You're very right, in that `guard-gradle` doesn't seem to have any kind of `./bin`— it looks like it's a plugin (of some kind) to guard itself.

After some messing around, I managed to get it to invoke via:

```Groovy
task guard(type: JRubyExec) {
    description 'Initiates project Guard watches.'
    script '/home/jake/Development/University/github/ghuman/build/tmp/jrubyExec/gems/guard-2.6.1/bin/guard'
}
```

But that's surely not the ideal way to invoke the script.  (If I added any `scriptArgs` to the above, guard complained about getting passed the arguments.)

D'you happen to know how I should be invoking the `guard` script from the guard gem itself?

**Comment by Dispader** [comment]
And I believe I know what was going wrong: my build.gradle specified a gem dependency for guard which was different from that defined by guard-gradle.

If it helps anyone else out— here's [a successful configuration](https://github.com/Dispader/example-jruby-gradle-plugin/tree/a118a6b0c8086d28a73c5f6e43e658d3b75e5642) for executing Guard, using the `guard-gradle` plugin, to watch a project from a Gradle task.

(Though you might want to update the jruby-gradle-plugin version from 1.9, if anyone uses this as a base.)

Thank you for all your help— and the great project!
