### ISSUE TITLE
Support for jBundler

### ISSUE THREAD

**Issue by swistaczek** [jruby-gradle/jruby-gradle-plugin#133]
Hi,
I would like to ask if this awesome gradle extension could support jbundler created by @mkristian?

**Comment by mkristian** [comment]
all those polyglot tools always try to bridge two worlds (or more). currently we are rounding up the gradle side of things. once this is done I am sure we look at how to use this extension in a more ruby like project, i.e. get the gem/jar dependencies from the Gemfile/Jarfile and/or gemspec file, etc.

parsing the Jarfile and add jar dependencies to the gradle configuration seems straight forward. any PR is most welcome ;)

**Comment by rtyler** [comment]
@swistaczek Can you expand on what you would imagine "supporting jbundler" would be? We've discussed supporting parsing Gemfiles before which makes sense to me since many Ruby developers are already quite familiar with their syntax and purpose for declaring strictly Ruby dependencies.

As a user of JBundler, I'm not sure what JRuby/Gradle would provide in terms of support?

**Comment by rtyler** [comment]
I'm going to go ahead and close this, I'm not sure there's anything we can/should do here. Please correct me if I'm wrong and we can reopen
