### ISSUE TITLE
jrubyArgs '-S' should be implicit in the JRubyExec task

### ISSUE THREAD

**Issue by rtyler** [jruby-gradle/jruby-gradle-plugin#152]
I've not yet seen a JRubyExec task where the expectation of "-S" isn't set, this makes sense to me to bring into the default mode of operation for `JRubyExec`

I think jrubyArgs should still exist, but we should have `setJRubyArgs` which replaces the default ("-S") and `jrubyArgs` which adds to it

**Comment by mkristian** [comment]
setting explicit -S is not needed in case there is script configured.

the problem is when you want to execute a script which is not on search path but on the current working directory ?

```setJRubyArgs``` sounds too complicated.

with jruby-maven-plugins the approach is to configure a "file" or a "command" (the one with -S) or  a script (inline script via -e) or just the args. and it uses the launch directory to be the project's directory. 

"file" and "command" can be combine if it is OK that ```jruby -S gem``` will give preference to the file "gem" on the launch directory, i.e. when the "script" is configured we prepend it with "-S" otherwise we use the ```jrubyArgs``` as we do now !

**Comment by ysb33r** [comment]
I don't agree. I think it just so happends that all of your use cases so far were just things that used scripts that were bundled with the supplied jruby-complete.

**Comment by mkristian** [comment]
so my suggestion (I was not clear enough) is

* there is script configured then add the ```-S``` (unless it is already there) which will work for all scripts whether they are local files or bundled with jruby-complete or somewhere on the PATH of the system
* there is no script configured but ```-e``` then leave it as is and do not add anything

this is a minimal change which is backward compatible and will relief the need to add ```-S``` manually but also works if you do add ```-S```
