### ISSUE TITLE
prepareJRubyJar doesn't cache results and reinstalls gems every single run

### ISSUE THREAD

**Issue by rtyler** [jruby-gradle/jruby-gradle-plugin#220]
Because we're now installing gems into `build/dirinfo/jrubyJar` by default, [this line](https://github.com/jruby-gradle/jruby-gradle-plugin/blob/29bcf7a7337d2b5a0b643dcb196c151a94e53a3a/jruby-gradle-jar-plugin/src/main/groovy/com/github/jrubygradle/jar/internal/JRubyDirInfo.groovy#L18) ensures that the directory is completely cleaned every time the `JRubyDirInfo` object is instantiated.

This is obviously problematic. And this should be backported to v1.0.4

Originally identified as jruby-gradle/jruby-gradle-storm-plugin#22

**Comment by mkristian** [comment]
this current implementation is problematic due to following issues:

* collecting the dir data in memory is not possible since this hook https://github.com/jruby-gradle/jruby-gradle-plugin/blob/29bcf7a7337d2b5a0b643dcb196c151a94e53a3a/jruby-gradle-jar-plugin/src/main/groovy/com/github/jrubygradle/jar/JRubyJar.groovy#L245 is just a visitor and there is no "end of visit" callback
* the relative path of the visitor is the source path and the not the target path which can be different

+1 for a better implementation

**Comment by rtyler** [comment]
I think I'll remove the `deleteDir` from now to prevent this regression and open another enhancement request to more cleanly stage and generate the `.jrubydir` information when we create the jar artifact instead of the stage directory
