### ISSUE TITLE
jrubyPrepare fails to resolve dependencies like 1.5.0.alpha.8

### ISSUE THREAD

**Issue by xlijun** [jruby-gradle/jruby-gradle-plugin#325]
Backgroud: 
I am trying to requires asciidoctor-pdf-cjk-kai_gen_gothic into asciidoc gradle plugin. 

Error Message (from jrubyPrepare): 
Could not find any matches for rubygems:asciidoctor-pdf:[1.5.0.alpha.8-SNAPSHOT,1.5.99999] as no versions of rubygems:asciidoctor-pdf are available.

Configuration:
```groovy
buildscript {
  ...
  dependencies {
    'com.github.jruby-gradle:jruby-gradle-plugin:1.5.0'
  }
}
apply plugin: "com.github.jruby-gradle.base"
dependencies {
    gems "rubygems:asciidoctor-pdf-cjk-kai_gen_gothic:0.1.1"
}
asciidoctor {
  ...
  dependsOn test
  dependsOn jrubyPrepare
  gemPath jrubyPrepare.outputDir

  attributes 'pdf-style': 'KaiGenGothicCN'
  requires 'asciidoctor-pdf-cjk-kai_gen_gothic'
  ...
}
```
It seems like the version resolution algorithm used by jrubyPrepare is not fully compatible with native ruby.

**Comment by mkristian** [comment]
@smartg00se you are right the gradle version resolution or the underlying mapping from rubygems to maven is not 100% compatible. for example it will not pick prereleased versions of gems from a range of versions, otherwise we would default to `--prerelease` install gems which is rarely what you want.

the maven repository excludes these prerelease version from the version range BUT they can be cherrypicked. so the only workaround for you is to add a gem dependency `rubygems asciidoctor-pdf 1.5.0.alpha.8`. once there is a released version of this gem you can remove this cherrypick.

**Comment by smartg00se** [comment]
I've tried to cherrypick `rubygems asciidoctor-pdf 1.5.0.alpha.8`, however the resolution also fails with the same exception above. It seems 1.5.0.alpha.8 is not treated as in the range [1.5.0.alpha.8-SNAPSHOT,1.5.99999].

**Comment by ysb33r** [comment]
@xlijun This issue does show a defect, but before I address the potential solution to this, I would to say that if you use a GEM that has `asciidoctor` or `asciidoctor-pdf` has a transitive dependency you should exclude those, because they are bundled within the specific `asciidoctorj` and `asciidoctorj-pdf` JARS. So you would do

```groovy 
dependencies {
    gems 'rubygems:asciidoctor-pdf-cjk-kai_gen_gothic:0.1.1', {
        exclude module : 'asciidoctor-pdf'
    }
}
```

**Comment by ysb33r** [comment]
Now as to the fix for the most general case, I now have a solution that will go in to 2.0.0 when it is released. The idea with the fix is that specific configurations or just modules can use Gradle's standard Ivy resolution rules rather the GEM version (bundler-like) resolution rules.

```groovy
        gemGroups {
            excludeModule ~/^asciidoctor-pdf$/, ~/.+(alpha|beta).*/ 
        }
        
        dependencies {
            gems 'rubygems:asciidoctor-pdf-cjk-kai_gen_gothic:0.1.1'
            gems 'rubygems:asciidoctor-pdf:1.5.0.alpha.8'
        }
```

In `gemGroups` one would be able to configure the behaviour of the `GemVersionResolver`. In this case we specifically exclude `asciidoctor-pdf`, but allow `asciidoctor-pdf-cjk*` to be resolved by bundler-like rules.

**Comment by ysb33r** [comment]
PR #377 addresses this.

**Comment by rtyler** [comment]
I'm going to close this, the work that @ysb33r I believe do address this use case, and will be documented as part of #378
