### ISSUE TITLE
[2.0.0-alpha.3] Installs a different version of a gem specified

### ISSUE THREAD

**Issue by boris-petrov** [jruby-gradle/jruby-gradle-plugin#394]
```gradle
buildscript {
	repositories {
		maven {
			url 'https://dl.bintray.com/jruby-gradle/plugins'
		}
	}
}

plugins {
	id 'com.github.jruby-gradle.base' version '2.0.0-alpha.3'
}

repositories {
	jcenter()
	ruby.gems()
}

dependencies {
	gems 'rubygems:selenium-webdriver:3.142.6'
	gems 'rubygems:webdrivers:4.1.3'
}
```

Running `gradle jrubyPrepare` on this emits the following output:

```
Successfully installed mini_portile2-2.4.0
Successfully installed nokogiri-1.10.7-java
Successfully installed rubyzip-2.0.0
Successfully installed childprocess-3.0.0
Successfully installed selenium-webdriver-4.0.0.alpha3
Successfully installed webdrivers-4.1.3
```

As you can see, the installed version of `selenium-webdriver` is `4.0.0.alpha3` while `3.142.6` is requested. This totally breaks the usage of that gem.

**Comment by Mogztter** [comment]
@boris-petrov To ease the resolution, could you confirm that this is a regression in 2.0.0-alpha.3. In other words do you reproduce this issue with 2.0.0-alpha.2 or 2.0.0-alpha.1? (not sure if alpha.1 or alpha.2 still relies on torquebox proxy though)

**Comment by Mogztter** [comment]
@ysb33r I can look into this issue tomorrow if you want?

**Comment by boris-petrov** [comment]
@Mogztter - thanks for looking into this. The same thing happens on both `2.0.0-alpha2` and `2.0.0-alpha1` so it is a "regression" from `1.7.0`.

**Comment by ysb33r** [comment]
@Mogztter it would be great if you can.

**Comment by Mogztter** [comment]
Ok, looking at it right now 👀
Thanks for the clarification @boris-petrov

**Comment by Mogztter** [comment]
It's a bug in the GemVersion resolution when there's multiple requirements. Currently the following requirements do not produce the expected result:

```rb
gem 'library', '~> 2.2', '>= 2.2.1' # translates to '>= 2.2.1, < 2.3.0'
```

**Comment by Mogztter** [comment]
I think I've found three issues with the current implementation.

#### Intersection

`'[1.2.1,1.2.4]'.intersect(']1.2.1,1.2.4[')` returns `']1.2.1,1.2.4[`'.

I believe this is wrong because the intersection is the set containing all elements of A that also belong to B.
In the above example `1.2.1` is non inclusive in the second definition. Similarly `1.2.4` is also non inclusive. As far as I understand, the intersection set should contain version `1.2.2` and `1.2.3` or using the ivy notation: `]1.2.1,1.2.4[`. In other words, the second definition is more restrictive and exclude both version `1.2.1` and `1.2.4` from the intersection.

#### union vs intersect

The `singleGemVersionFromMultipleGemRequirements` method uses `union` to combine multiple requirements but requirements are additive. So I think we should `intersect` and not `union`.

For instance, let's say that I have the following requirements:

- version must be greater than 3.0.0 and lower than 3.5.0
- version must be lower than 4.0.0
- version must be greater than 3.1.0

What I want is to meet all requirements, so my version range will be the intersection: `]3.1.0,3.5.0[`

#### union with min/max

In the `union` method we are using `min` and `max` which rely on `compareTo`. I don't think we can use `min` and `max` in this context. What we want is the the lowest low value of two requirements and the highest high value of those same requirements.
But it does not matter much since we won't use this method anymore.

Am I missing something?

**Comment by ysb33r** [comment]
I think you are right.

**Comment by boris-petrov** [comment]
@Mogztter - thanks for working on this! However, I get the same behavior on `alpha.4`, not sure why. I think I've cleaned all caches and when I use the exact same `build.gradle` (but changing the plugin version of course) as in the original post, I get the same result. Am I missing something?

**Comment by Mogztter** [comment]
Not sure... Could you please share a simplified `build.gradle` that reproduces this issue?

FYI I've added an integration test with your dependencies (see: https://github.com/jruby-gradle/jruby-gradle-plugin/pull/396/files#diff-d6117fc30ea3474dc90f0d3abe4d6460R80)

**Comment by boris-petrov** [comment]
@Mogztter - I saw the test, yes. This is the simplest `build.gradle`:

```gradle
plugins {
	id 'com.github.jruby-gradle.base' version '2.0.0-alpha.4'
}

repositories {
	jcenter()
	ruby.gems()
}

dependencies {
	gems 'rubygems:selenium-webdriver:3.142.6'
	gems 'rubygems:webdrivers:4.1.3'
}
```

If you run `gradle jrubyPrepare` you should see the same (version 4 of Selenium installed). Please confirm or deny - it's possible that I have some caching issue in Gradle or something.

**Comment by Mogztter** [comment]
I won't be able to check until next week as I'm on vacation :grimacing:

**Comment by boris-petrov** [comment]
@ysb33r - do you mind trying this `build.gradle` file from my previous comment and writing here whether it installs the correct Selenium version please? I don't understand how Gradle caches work and I'm not sure whether I'm not mistaking something.

**Comment by ysb33r** [comment]
@boris-petrov I am going to give this a quick go.

**Comment by ysb33r** [comment]
@boris-petrov 

I got 
```
gradle -u dep --configuration gems

> Task :dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

gems
+--- rubygems:selenium-webdriver:3.142.6
|    +--- rubygems:childprocess:[0.5,4.0[ -> 3.0.0
|    \--- rubygems:rubyzip:[1.2.2,) -> 2.0.0
\--- rubygems:webdrivers:4.1.3
     +--- rubygems:nokogiri:[1.6.0,2.0[ -> 1.10.7
     |    \--- rubygems:mini_portile2:[2.4.0,2.5.0[ -> 2.4.0
     +--- rubygems:rubyzip:[1.3.0,) -> 2.0.0
     \--- rubygems:selenium-webdriver:[3.0,4.0[ -> 3.142.6
```
then when running `gradle jrubyPrepare`
```
Successfully installed mini_portile2-2.4.0
Successfully installed nokogiri-1.10.7-java
Successfully installed rubyzip-2.0.0
Successfully installed childprocess-3.0.0
Successfully installed selenium-webdriver-3.142.6
Successfully installed webdrivers-4.1.3
```
I suspect it might be caching and you have residue because of the previous bug.

Delete the `~/.gradle/rubygems-ivyxml-cache/` folder and try again.

**Comment by boris-petrov** [comment]
@ysb33r - great, thanks, I'll try that!
